#!/usr/bin/env bash
# One-command Nintendo Switch build for MarathonRecomp.
#
# Run from an MSYS2 shell. See docs/BUILDING-SWITCH.md for full details.
#
# Prerequisites:
#   - devkitPro + devkitA64            (DEVKITPRO, default /opt/devkitpro)
#   - MSYS2 CLANGARM64: clang cmake ninja
#   - MSYS2 CLANG64:    clang          (only for the x64 shader tool; see NOTE below)
#
# Inputs you supply (kept out of the repo):
#   - Game files in MarathonRecompLib/private/ : default.xex, shader.arc, shader_lt.arc
#   - NVK Vulkan driver: NVK_ROOT -> extracted mesa build dir containing
#         builddir-switch/src/nouveau/vulkan/libvulkan.a
#     (closed/unshipped; provide your own.)
#
# Usage:
#   NVK_ROOT=/c/path/to/mesa-nvk  tools/build-switch.sh
#
# NOTE: the bundled arm64 DXC emits invalid SPIR-V, so the game shader cache is
# generated by an x86_64 build of XenosRecomp driving the x64 DXC (runs under
# emulation on Windows-ARM). That is why CLANG64 is required.
set -euo pipefail

: "${DEVKITPRO:=/opt/devkitpro}"
: "${NVK_ROOT:?Set NVK_ROOT to your extracted mesa-nvk dir (contains builddir-switch/src/nouveau/vulkan/libvulkan.a).}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 8)}"

CLANGARM64="${CLANGARM64:-/c/msys64/clangarm64/bin}"
CLANG64="${CLANG64:-/c/msys64/clang64/bin}"
CMAKE="$CLANGARM64/cmake.exe"
NINJA="$CLANGARM64/ninja.exe"

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root_dir"

NVK_LIB="$NVK_ROOT/builddir-switch/src/nouveau/vulkan/libvulkan.a"
DXC_X64="$root_dir/tools/XenosRecomp/thirdparty/dxc-bin/bin/x64"

log() { echo; echo "==== $* ===="; }

# ---------------------------------------------------------------- preconditions
for f in default.xex shader.arc shader_lt.arc; do
  [ -f "MarathonRecompLib/private/$f" ] || { echo "Missing MarathonRecompLib/private/$f (copy from your game dump)." >&2; exit 2; }
done
[ -f "$NVK_LIB" ] || { echo "NVK driver not found: $NVK_LIB" >&2; exit 2; }
[ -x "$CMAKE" ] || { echo "cmake not found at $CMAKE (install MSYS2 clangarm64 cmake)." >&2; exit 2; }
[ -x "$CLANG64/clang.exe" ] || { echo "clang64 not found at $CLANG64 (pacman -S mingw-w64-clang-x86_64-clang)." >&2; exit 2; }

# ------------------------------------------------------------- 1. apply patches
log "1/8 apply submodule patches"
apply_patch() { # $1 patch file, $2 submodule dir
  local p="$root_dir/patches/$1"
  [ -f "$p" ] || return 0
  ( cd "$2" 2>/dev/null || exit 0
    if   git apply --check "$p" 2>/dev/null; then git apply "$p"; echo "  applied $1"
    elif git apply --reverse --check "$p" 2>/dev/null; then echo "  $1 already applied"
    else echo "  WARNING: $1 did not apply cleanly" >&2; fi )
}
apply_patch volk.patch                    thirdparty/plume/contrib/volk
apply_patch plume.patch                   thirdparty/plume
apply_patch imgui.patch                   thirdparty/imgui
apply_patch implot.patch                  thirdparty/implot
apply_patch concurrentqueue.patch         thirdparty/concurrentqueue
apply_patch XenonRecomp.patch             tools/XenonRecomp
apply_patch XenosRecomp.patch             tools/XenosRecomp
apply_patch XenosRecomp-mingw-dxc.patch   tools/XenosRecomp
apply_patch tomlplusplus-msys-host.patch  tools/XenonRecomp/thirdparty/tomlplusplus

# --------------------------------------------------- 2. host tools (arm64, native)
log "2/8 build host tools (arm64)"
CC="$CLANGARM64/clang.exe" CXX="$CLANGARM64/clang++.exe" \
"$CMAKE" -S . -B build/host-tools -G Ninja -DCMAKE_BUILD_TYPE=Release \
  -DMARATHON_RECOMP_HOST_TOOLS_ONLY=ON -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
  -DCMAKE_CXX_FLAGS="-include cstdlib -include cstdio" -DCMAKE_MAKE_PROGRAM="$NINJA"
"$CMAKE" --build build/host-tools -j"$JOBS" --target XenonRecomp file_to_c u8extract x_decompress

# ---------------------------- 3. host tool XenosRecomp (x86_64 cross, for x64 DXC)
log "3/8 build XenosRecomp (x64, for x64 DXC)"
PATH="$CLANG64:$DXC_X64:$PATH" CC="$CLANG64/clang.exe" CXX="$CLANG64/clang++.exe" \
"$CMAKE" -S . -B build/host-tools-x64 -G Ninja \
  -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=AMD64 \
  -DCMAKE_BUILD_TYPE=Release -DMARATHON_RECOMP_HOST_TOOLS_ONLY=ON \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
  -DCMAKE_CXX_FLAGS="-include cstdlib -include cstdio" -DCMAKE_MAKE_PROGRAM="$NINJA"
"$CMAKE" --build build/host-tools-x64 -j"$JOBS" --target XenosRecomp

# ------------------------------------------------------- 4. recompile PPC from XEX
log "4/8 recompile PPC from default.xex"
build/host-tools/tools/XenonRecomp/XenonRecomp/XenonRecomp.exe \
  MarathonRecompLib/config/Marathon.toml tools/XenonRecomp/XenonUtils/ppc_context.h

# --------------------------------------------------------- 5. generate shaders
log "5/8 generate shader cache + app shaders"
U8="build/host-tools/tools/u8extract/u8extract.exe"
XS="build/host-tools-x64/tools/XenosRecomp/XenosRecomp/XenosRecomp.exe"
rm -rf MarathonRecompLib/private/shader; mkdir -p MarathonRecompLib/private/shader
"$U8" MarathonRecompLib/private/shader.arc    MarathonRecompLib/private/shader
"$U8" MarathonRecompLib/private/shader_lt.arc MarathonRecompLib/private/shader
PATH="$DXC_X64:$PATH" "$XS" MarathonRecompLib/private/shader \
  MarathonRecompLib/shader/shader_cache.cpp tools/XenosRecomp/XenosRecomp/shader_common.h
bash tools/generate-switch-app-shaders.sh

# ------------------------------------------------------------------ 6. ffmpeg
log "6/8 cross-build FFmpeg (avcodec+avutil, XMAFRAMES)"
DEVKITPRO="$DEVKITPRO" JOBS="$JOBS" bash tools/build-switch-ffmpeg.sh

# ------------------------------------------------- 7. configure + build the app
log "7/8 configure + cross-compile the Switch app"
export DEVKITPRO
PATH="$DEVKITPRO/devkitA64/bin:$PATH" \
"$CMAKE" -S . -B build/switch-app -G Ninja \
  -DCMAKE_TOOLCHAIN_FILE=toolchains/switch-devkitA64.cmake -DCMAKE_BUILD_TYPE=Release \
  -DMARATHON_RECOMP_SWITCH=ON \
  -DMARATHON_RECOMP_SWITCH_USE_PREGENERATED_SHADERS=ON \
  -DMARATHON_RECOMP_SWITCH_USE_PREGENERATED_APP_SHADERS=ON \
  -DMARATHON_RECOMP_SWITCH_USE_PREGENERATED_PPC=ON \
  -DMARATHON_RECOMP_HOST_TOOLS_DIR="$root_dir/build/host-tools" \
  -DMARATHON_RECOMP_HOST_FILE_TO_C="$root_dir/build/host-tools/tools/file_to_c/file_to_c.exe" \
  -DPLUME_PLATFORM_SWITCH=ON -DPLUME_SWITCH_NVK_ROOT="$NVK_ROOT" -DPLUME_SWITCH_NVK_LIBRARY="$NVK_LIB" \
  -DCMAKE_MAKE_PROGRAM="$NINJA"
PATH="$DEVKITPRO/devkitA64/bin:$PATH" "$CMAKE" --build build/switch-app -j"$JOBS" --target MarathonRecomp

# ------------------------------------------------------------------ 8. package
log "8/8 package NRO"
DEVKITPRO="$DEVKITPRO" bash tools/package-switch-nro.sh

echo; echo "==== Switch build complete: dist/switch/MarathonRecomp.nro ===="
