#!/usr/bin/env bash
# One-command Nintendo Switch build for MarathonRecomp.
#
# Run from an MSYS2 or Git Bash shell. See docs/BUILDING-SWITCH.md for full details.
#
# Prerequisites:
#   - devkitPro + devkitA64            (DEVKITPRO; default /opt/devkitpro, else C:/devkitPro)
#   - MSYS2 clang, cmake and ninja for the host tools: CLANGARM64 on an arm64 PC, CLANG64 on an x86_64 PC
#     (found under C:/devkitPro/msys2 or C:/msys64; set CLANGARM64=/CLANG64= to the bin folders to override)
#   - MSYS2 CLANG64:    clang          (only for the x64 shader tool; see NOTE below)
#   - Python 3 (python3, python or py, Windows or MSYS2; PYTHON= to choose) for SWITCH_DIRECT_CALLS
#
# Inputs you supply (kept out of the repo):
#   - Game files in MarathonRecompLib/private/ : default.xex, shader.arc, shader_lt.arc
#   - NVK Vulkan driver: NVK_ROOT -> extracted Switch SDK containing
#         lib/libvulkan.a, a mesa-switch tree built with build-unified.sh (its
#         mesa-unified-install/opt/devkitpro/portlibs/switch/lib/libvulkan.a), or a legacy Mesa tree containing
#         builddir-switch/src/nouveau/vulkan/libvulkan.a
#     (closed/unshipped; provide your own.)
#
# Usage:
#   NVK_ROOT=/c/path/to/mesa-nvk  tools/build-switch.sh
#
# Build switches (docs/BUILDING-SWITCH.md):
#   SWITCH_APP_ONLY=0         1: rebuild only the app from the generated sources of an earlier full build
#                             (skips steps 1-6: patches, host tools, PPC and shader generation, FFmpeg)
#   SWITCH_SKIP_PATCHES=0     1: leave the submodule trees as they are (hand-edited trees); no reset, no patching
#   SWITCH_DIRECT_CALLS=1     calls between recompiled functions made direct so GCC can inline them
#                             (tools/switch-direct-calls.py; the linked ELF is checked against the hooks); 0 undoes them
#   SWITCH_HOT_FUNCTIONS=1    passed to tools/switch-direct-calls.py (0: no .text.hot marking; 0 in classic builds)
#   SWITCH_LTO=0              1: link-time optimisation (needs a lot of build RAM and time)
#   SWITCH_LTO_JOBS=2         parallel LTRANS jobs when SWITCH_LTO=1
#   SWITCH_PGO=               empty, "generate" (instrumented build, no LTO) or "use"
#   SWITCH_PGO_DIR=pgo        folder with the .gcda files copied from sdmc:/switch/MarathonRecomp/pgo
#   SWITCH_O2=0               1: all the code with -O2 instead of -O3
#   SWITCH_RECOMP_O2=0        1: the recompiled code with -O2 instead of -O3
#   SWITCH_IPA_PTA=0          1: compile and link with -fipa-pta (whole-program points-to analysis at the LTO link)
#   SWITCH_CLASSIC_CODEGEN=0  1: ppc/ generated by XenonRecomp's classic code generation, for A/B builds
#   SWITCH_FIXED_X16=1        x16 kept out of register allocation (exception_switch.cpp resumes through it)
#   SWITCH_EXACT_FMA=0        1: Xbox 360-exact fused multiply-add rounding; changes the last bit of some float results
#                             compared with builds without it (-ffp-contract=off + explicit fma). Needs ppc/ with the
#                             explicit fma text (XenonRecomp-switch-perf.patch); without it, and with
#                             SWITCH_CLASSIC_CODEGEN=1, it is turned off with a message. Not exact with SWITCH_LTO=1
#                             (docs/BUILDING-SWITCH.md)
#   Code generation of the recompiled game (ppc/ is regenerated when they change; tools/switch-codegen-pass.py):
#   SWITCH_LEAF_LOCALS=1      leaf functions keep the context's registers in locals
#   SWITCH_WIDE_DFORM=1       register + displacement loads and stores as 64-bit addresses (the same accesses; a
#                             wrap past 4 GB lands in the guard after the window, emulated at the wrapped address)
#   SWITCH_CONST_VMX_TABLES=1 lvx/stvx/lvlx/lvrx byte shuffles as plain NEON TBL
#   SWITCH_INLINE_FP_COMPARE=1  fcmpu/fcmpo compare branchless and always inlined
#   SWITCH_INLINE_MEMCPY=1    fixed-size guest memmove/memset calls as inline builtins
#   SWITCH_CALL_LOCALS=1      (perf7) the profile-hot functions that call keep the registers in locals between calls
#                             (MarathonRecompLib/config/call_locals.txt; no floating-point products)
#   SWITCH_FPSCR_LOCALS=1     (perf7) the FPSCR mode word as a local in those and in leaf functions without FP products
#   SWITCH_PREFETCH_HINTS=1   (perf7) host prefetches of guest objects in a few hot functions (tools/switch-codegen-pass.py)
#   SWITCH_FP_LEAF_LOCALS=1   (perf7) leaf locals for scalar floating-point leaves where no product reaches a sum
#   SWITCH_FP_SINGLE_MODE=1   (perf7) the MOPP query in locals, without contraction, its vector code in the scalar mode
#   SWITCH_FP_NO_CONTRACT=1   (perf7) hot floating-point functions in locals without contraction, where that is what GCC
#                             made of them before (MarathonRecompLib/config/fp_no_contract.txt)
#   SWITCH_FP_INT_LOCALS=1    (perf8) the other floating-point functions keep their integer registers in locals, their
#                             floating-point registers in the context as before
#   SWITCH_REGISTER_LOCALS=1  CR, CTR, XER and the reservation as locals, no LR/MSR (XenonRecomp; console-tested in perf4/5)
#   SWITCH_FEWER_MODE_SWITCHES=1  XenonRecomp keeps a known FPCR flush mode for instructions whose result does not
#                             depend on it (exact helpers in ppc_context.h; UnleashedRecomp-NX round 14)
#   SWITCH_PLAIN_GUEST_MEMORY=1  guest memory accesses not volatile (loop barriers instead; console-tested in perf4/5)
#   SWITCH_NARROW_BARRIER=1   (with SWITCH_PLAIN_GUEST_MEMORY) loop barriers cover guest memory only, not the context
#   SWITCH_BUILD_ID=          names the build (switch_build_id.h); default: date, time and the options above
#
# Generated outputs are reused while their inputs are unchanged: the submodule patches (build/patch-stamps),
# ppc/ (MarathonRecompLib/ppc/ppc_codegen_stamp.txt), the shader cache (shader_cache.cpp.translator) and the
# app shaders (build/switch-stamps). Delete a stamp to force that step.
#
# NOTE: the bundled arm64 DXC emits invalid SPIR-V, so the game shader cache is
# generated by an x86_64 build of XenosRecomp driving the x64 DXC (runs under
# emulation on Windows-ARM). That is why CLANG64 is required.
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root_dir"

log() { echo; echo "==== $* ===="; }
die() { echo "$*" >&2; exit 2; }

# ------------------------------------------------------------------ options
bool_option() { # $1 variable, $2 default: 1/on/true/yes -> 1, 0/off/false/no -> 0
  local value
  value="$(printf '%s' "${!1:-$2}" | tr '[:upper:]' '[:lower:]')"
  case "$value" in
    1|on|true|yes) printf -v "$1" '%s' 1 ;;
    0|off|false|no) printf -v "$1" '%s' 0 ;;
    *) die "$1 must be 0 or 1 (is '${!1}')." ;;
  esac
}
for option_default in SWITCH_APP_ONLY=0 SWITCH_SKIP_PATCHES=0 SWITCH_DIRECT_CALLS=1 SWITCH_LTO=0 SWITCH_O2=0 \
    SWITCH_RECOMP_O2=0 SWITCH_IPA_PTA=0 SWITCH_CLASSIC_CODEGEN=0 SWITCH_FIXED_X16=1 SWITCH_EXACT_FMA=0 \
    SWITCH_LEAF_LOCALS=1 SWITCH_CONST_VMX_TABLES=1 SWITCH_INLINE_FP_COMPARE=1 SWITCH_INLINE_MEMCPY=1 \
    SWITCH_REGISTER_LOCALS=1 SWITCH_PLAIN_GUEST_MEMORY=1 SWITCH_NARROW_BARRIER=1 SWITCH_WIDE_DFORM=1 \
    SWITCH_FEWER_MODE_SWITCHES=1 SWITCH_HOT_FUNCTIONS=1 SWITCH_CALL_LOCALS=1 SWITCH_FPSCR_LOCALS=1 SWITCH_PREFETCH_HINTS=1 SWITCH_FP_LEAF_LOCALS=1 SWITCH_FP_SINGLE_MODE=1 \
    SWITCH_FP_NO_CONTRACT=1 SWITCH_FP_INT_LOCALS=1; do
  bool_option "${option_default%%=*}" "${option_default#*=}"
done
SWITCH_LTO_JOBS="${SWITCH_LTO_JOBS:-2}"
SWITCH_PGO="${SWITCH_PGO:-}"
SWITCH_PGO_DIR="${SWITCH_PGO_DIR:-pgo}"
case "$SWITCH_LTO_JOBS" in
  auto|[1-9]|[1-9][0-9]) ;;
  *) die "SWITCH_LTO_JOBS must be a number or auto (is '$SWITCH_LTO_JOBS')." ;;
esac
case "$SWITCH_PGO" in
  ""|generate|use) ;;
  *) die "SWITCH_PGO must be empty, generate or use (is '$SWITCH_PGO')." ;;
esac
if [ "$SWITCH_PGO" = "generate" ] && [ "$SWITCH_LTO" = "1" ]; then
  die "SWITCH_PGO=generate needs SWITCH_LTO=0 (instrumented builds are not linked with LTO)."
fi
# The classic text has no explicit fma: -ffp-contract=off would round every guest fused operation twice.
if [ "$SWITCH_CLASSIC_CODEGEN" = "1" ] && [ "$SWITCH_EXACT_FMA" = "1" ]; then
  echo "SWITCH_EXACT_FMA=1 is ignored with SWITCH_CLASSIC_CODEGEN=1 (GCC's default contraction is used)."
  SWITCH_EXACT_FMA=0
fi
# The classic A/B build is XenonRecomp's previous output: none of the newer code generation options apply to it.
if [ "$SWITCH_CLASSIC_CODEGEN" = "1" ]; then
  SWITCH_LEAF_LOCALS=0; SWITCH_CONST_VMX_TABLES=0; SWITCH_INLINE_FP_COMPARE=0; SWITCH_INLINE_MEMCPY=0
  SWITCH_REGISTER_LOCALS=0; SWITCH_PLAIN_GUEST_MEMORY=0; SWITCH_NARROW_BARRIER=0; SWITCH_WIDE_DFORM=0
  SWITCH_FEWER_MODE_SWITCHES=0; SWITCH_CALL_LOCALS=0; SWITCH_FPSCR_LOCALS=0; SWITCH_PREFETCH_HINTS=0; SWITCH_FP_LEAF_LOCALS=0; SWITCH_FP_SINGLE_MODE=0; SWITCH_FP_NO_CONTRACT=0; SWITCH_FP_INT_LOCALS=0
fi
# The narrow barrier only exists for plain guest memory (with volatile accesses the barriers are empty).
if [ "$SWITCH_PLAIN_GUEST_MEMORY" != "1" ]; then SWITCH_NARROW_BARRIER=0; fi
codegen_pass_options="SWITCH_LEAF_LOCALS=$SWITCH_LEAF_LOCALS SWITCH_CONST_VMX_TABLES=$SWITCH_CONST_VMX_TABLES"
codegen_pass_options+=" SWITCH_INLINE_FP_COMPARE=$SWITCH_INLINE_FP_COMPARE SWITCH_INLINE_MEMCPY=$SWITCH_INLINE_MEMCPY"
codegen_pass_options+=" SWITCH_NARROW_BARRIER=$SWITCH_NARROW_BARRIER SWITCH_WIDE_DFORM=$SWITCH_WIDE_DFORM"
codegen_pass_options+=" SWITCH_CALL_LOCALS=$SWITCH_CALL_LOCALS SWITCH_FPSCR_LOCALS=$SWITCH_FPSCR_LOCALS"
codegen_pass_options+=" SWITCH_PREFETCH_HINTS=$SWITCH_PREFETCH_HINTS SWITCH_FP_LEAF_LOCALS=$SWITCH_FP_LEAF_LOCALS"
codegen_pass_options+=" SWITCH_FP_SINGLE_MODE=$SWITCH_FP_SINGLE_MODE SWITCH_FP_NO_CONTRACT=$SWITCH_FP_NO_CONTRACT"
codegen_pass_options+=" SWITCH_FP_INT_LOCALS=$SWITCH_FP_INT_LOCALS"

# The default build ID is made at the configure step (7), once ppc/ has decided SWITCH_EXACT_FMA.
build_id_default=false
if [ -z "${SWITCH_BUILD_ID:-}" ]; then
  build_id_default=true
else
  case "$SWITCH_BUILD_ID" in
    *[\"\\\;]*) die "SWITCH_BUILD_ID may not contain quotes, backslashes or semicolons." ;;
  esac
  echo "Build ID: $SWITCH_BUILD_ID"
fi

# --------------------------------------------------------------------- host
# devkitPro. Git Bash exports DEVKITPRO=/opt/devkitpro even where that folder does not exist.
if [ -z "${DEVKITPRO:-}" ] || [ ! -d "$DEVKITPRO" ]; then
  for devkitpro_candidate in /opt/devkitpro /c/devkitPro; do
    if [ -d "$devkitpro_candidate" ]; then DEVKITPRO="$devkitpro_candidate"; break; fi
  done
fi
: "${DEVKITPRO:=/opt/devkitpro}"
# cmake and the native devkitA64 tools take the Windows form (C:/devkitPro), the shell the POSIX one.
DEVKITPRO_SHELL="$DEVKITPRO"
if command -v cygpath >/dev/null 2>&1; then
  DEVKITPRO="$(cygpath -m "$DEVKITPRO")"
  DEVKITPRO_SHELL="$(cygpath -u "$DEVKITPRO")"
fi
[ -d "$DEVKITPRO_SHELL/devkitA64/bin" ] || die "devkitA64 not found under DEVKITPRO=$DEVKITPRO_SHELL."
: "${NVK_ROOT:?Set NVK_ROOT to your extracted Mesa/NVK Switch SDK or build tree.}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 8)}"

# Host tools are native: MSYS2 CLANGARM64 on an arm64 PC, CLANG64 on an x86_64 PC (where an installed
# clangarm64 cannot run). devkitPro's own MSYS2 (C:/devkitPro/msys2) is preferred when it has the tools.
host_is_arm64=false
case "$(uname -m 2>/dev/null) ${PROCESSOR_ARCHITECTURE:-} ${PROCESSOR_IDENTIFIER:-}" in
  *aarch64*|*arm64*|*ARM64*|*ARMv8*) host_is_arm64=true ;;
esac
first_clang_dir() { # the first folder that holds clang.exe, else the first one
  local dir
  for dir in "$@"; do
    if [ -x "$dir/clang.exe" ]; then echo "$dir"; return 0; fi
  done
  echo "$1"
}
CLANG64="${CLANG64:-$(first_clang_dir /c/devkitPro/msys2/clang64/bin /c/msys64/clang64/bin)}"
if [ -z "${CLANGARM64:-}" ]; then
  if $host_is_arm64; then
    CLANGARM64="$(first_clang_dir /c/msys64/clangarm64/bin /c/devkitPro/msys2/clangarm64/bin "$CLANG64")"
  else
    CLANGARM64="$CLANG64"
  fi
fi
CMAKE="$CLANGARM64/cmake.exe"
NINJA="$CLANGARM64/ninja.exe"
# Paths handed to the native cmake in Windows form (not left to the shell's argument conversion).
root_native="$root_dir"
NINJA_NATIVE="$NINJA"
if command -v cygpath >/dev/null 2>&1; then
  root_native="$(cygpath -m "$root_dir")"
  NINJA_NATIVE="$(cygpath -m "$NINJA")"
fi
# The host tools built with that clang (XenonRecomp, u8extract...) need its runtime DLLs (libc++, libunwind)
# when they run in steps 4 and 5; an MSYS or Git Bash shell does not have them on PATH.
export PATH="$CLANGARM64:$PATH"

PYTHON="${PYTHON:-}"
require_python() { # finds a working Python 3 once (Windows python, py or MSYS2 python3 all work)
  local candidate
  if [ -n "$PYTHON" ]; then
    "$PYTHON" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 6) else 1)' >/dev/null 2>&1 ||
      die "PYTHON=$PYTHON is not a working Python 3."
    return 0
  fi
  for candidate in python3 python py /c/devkitPro/msys2/usr/bin/python3 /c/msys64/usr/bin/python3; do
    if command -v "$candidate" >/dev/null 2>&1 &&
       "$candidate" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 6) else 1)' >/dev/null 2>&1; then
      PYTHON="$candidate"
      return 0
    fi
  done
  die "Python 3 is required for SWITCH_DIRECT_CALLS=1 (install it or set PYTHON=...; SWITCH_DIRECT_CALLS=0 builds without)."
}

# NVK driver: the SDK layout (lib/libvulkan.a) directly or inside a mesa-unified-install stage, or a legacy
# Mesa build tree. For the SDK layouts NVK_ROOT becomes the folder holding lib/ and include/.
NVK_LIB=""
for nvk_candidate_root in \
    "$NVK_ROOT" \
    "$NVK_ROOT/opt/devkitpro/portlibs/switch" \
    "$NVK_ROOT/mesa-unified-install/opt/devkitpro/portlibs/switch"; do
  if [ -f "$nvk_candidate_root/lib/libvulkan.a" ]; then
    NVK_ROOT="$nvk_candidate_root"
    NVK_LIB="$nvk_candidate_root/lib/libvulkan.a"
    break
  fi
done
if command -v cygpath >/dev/null 2>&1; then
  NVK_ROOT="$(cygpath -m "$NVK_ROOT")"
  [ -z "$NVK_LIB" ] || NVK_LIB="$(cygpath -m "$NVK_LIB")"
fi
if [ -n "$NVK_LIB" ]; then
  NVK_EXTRA_LIBS="-L$NVK_ROOT/lib;zstd;z;nx"
  # Current mesa-switch builds (build-unified.sh) compile Mesa's xmlconfig, which needs expat.
  if [ -f "$DEVKITPRO_SHELL/portlibs/switch/lib/libexpat.a" ]; then
    NVK_EXTRA_LIBS="-L$NVK_ROOT/lib;expat;zstd;z;nx"
  fi
elif [ -f "$NVK_ROOT/builddir-switch/src/nouveau/vulkan/libvulkan.a" ]; then
  NVK_LIB="$NVK_ROOT/builddir-switch/src/nouveau/vulkan/libvulkan.a"
  NVK_EXTRA_LIBS="drm_nouveau;zstd;z;nx"
else
  echo "NVK driver not found under $NVK_ROOT (expected lib/libvulkan.a, mesa-unified-install/opt/devkitpro/portlibs/switch/lib/libvulkan.a or builddir-switch/src/nouveau/vulkan/libvulkan.a)." >&2
  exit 2
fi
echo "NVK driver: $NVK_LIB"
DXC_X64="$root_dir/tools/XenosRecomp/thirdparty/dxc-bin/bin/x64"

case "$SWITCH_PGO_DIR" in
  /*|[A-Za-z]:*) ;;
  *) SWITCH_PGO_DIR="$root_dir/$SWITCH_PGO_DIR" ;;
esac
pgo_dir_shell="$SWITCH_PGO_DIR"
if command -v cygpath >/dev/null 2>&1; then
  pgo_dir_shell="$(cygpath -u "$SWITCH_PGO_DIR")"
  SWITCH_PGO_DIR="$(cygpath -m "$SWITCH_PGO_DIR")"
fi
if [ "$SWITCH_PGO" = "use" ] && ! compgen -G "$pgo_dir_shell/*.gcda" >/dev/null; then
  die "SWITCH_PGO=use: no .gcda files in $pgo_dir_shell (copy them from sdmc:/switch/MarathonRecomp/pgo)."
fi

# ------------------------------------------------------------- input hashing
file_id() { # sha256 of a file's content, "missing" when there is none
  if [ -f "$1" ]; then sha256sum < "$1" | cut -c1-64; else echo "missing"; fi
}
tree_state_id() { # $1 repository: its HEAD, tracked changes and untracked files (nested submodules aside)
  ( cd "$1" && {
      git rev-parse HEAD
      git diff HEAD --ignore-submodules --binary
      git ls-files -z --others --exclude-standard | xargs -0 -r sha256sum --
    } | sha256sum | cut -c1-64 )
}
patch_list_id() { # $@ patch names (?name: optional): the names and contents of those present
  local spec name
  for spec in "$@"; do
    name="${spec#\?}"
    if [ -f "patches/$name" ]; then echo "== $name"; cat "patches/$name"; else echo "== $name absent"; fi
  done | sha256sum | cut -c1-64
}
print_changed_keys() { # $1 stamp file, $2 new content: names the key=value lines that differ
  local key
  if [ -f "$1" ]; then
    for key in $(printf '%s\n' "$2" | grep -vxF -f "$1" | cut -d= -f1); do echo "    changed: $key"; done
  else
    echo "    (no stamp)"
  fi
}

ppc_dir="MarathonRecompLib/ppc"
codegen_stamp="$ppc_dir/ppc_codegen_stamp.txt"
direct_calls_tool="tools/switch-direct-calls.py"
codegen_pass_tool="tools/switch-codegen-pass.py"
direct_calls_manifest="$ppc_dir/ppc_direct_calls.txt" # written by the tool while its rewrites are in ppc/
shader_cache="MarathonRecompLib/shader/shader_cache.cpp"
shader_stamp="$shader_cache.translator"

# ------------------------------------------------------------ preconditions
[ -x "$CMAKE" ] || die "cmake not found at $CMAKE (install MSYS2 cmake, or set CLANGARM64 to a folder that has it)."
if [ "$SWITCH_APP_ONLY" = "1" ]; then
  for f in "$ppc_dir/ppc_recomp.0.cpp" "$codegen_stamp" "$shader_cache" \
      build/host-tools/tools/file_to_c/file_to_c.exe thirdparty/ffmpeg-core/switch/lib/libavcodec.a; do
    [ -f "$f" ] || die "SWITCH_APP_ONLY=1 reuses the outputs of a full build, but $f is missing."
  done
  grep -qx "classic=$SWITCH_CLASSIC_CODEGEN" "$codegen_stamp" ||
    die "ppc/ was generated with another SWITCH_CLASSIC_CODEGEN; build without SWITCH_APP_ONLY."
else
  for f in default.xex shader.arc shader_lt.arc; do
    [ -f "MarathonRecompLib/private/$f" ] || die "Missing MarathonRecompLib/private/$f (copy from your game dump)."
  done
  [ -x "$CLANG64/clang.exe" ] || die "clang64 not found at $CLANG64 (pacman -S mingw-w64-clang-x86_64-clang)."
fi
direct_calls_run=false
if [ -f "$direct_calls_tool" ] && { [ "$SWITCH_DIRECT_CALLS" = "1" ] || [ -f "$direct_calls_manifest" ]; }; then
  direct_calls_run=true
  require_python
fi

if [ "$SWITCH_APP_ONLY" = "1" ]; then
  log "1-6/8 skipped (SWITCH_APP_ONLY=1: patches, host tools, PPC, shaders and FFmpeg as generated before)"
else

# ------------------------------------------------------------- 1. apply patches
log "1/8 apply submodule patches"
# Each submodule is reset and its patches applied in order, but only when the patches changed or the tree no
# longer holds what they produced (build/patch-stamps: line 1 the patches, line 2 the tree after them). An
# unchanged tree keeps its timestamps, so the host tools and plume are not rebuilt.
apply_patches() { # $1 submodule, $2... patches/ files in order (?name: optional)
  local dir="$1"; shift
  local stamp_name stamp patches_id state spec name backup gitlink
  local apply_flags=(--ignore-space-change --whitespace=nowarn)
  stamp_name="$(echo "$dir" | tr '/' '_')"
  stamp="build/patch-stamps/$stamp_name.stamp"
  [ -e "$dir/.git" ] || die "  $dir is not checked out (git submodule update --init --recursive)."
  patches_id="$(patch_list_id "$@")"
  state="$(tree_state_id "$dir")"
  if [ -f "$stamp" ] && [ "$(sed -n 1p "$stamp")" = "$patches_id" ] && [ "$(sed -n 2p "$stamp")" = "$state" ]; then
    echo "  $dir: patches already applied"
    return 0
  fi

  # Changes that are not what the recorded patches produced (hand edits, new files) are kept before the reset.
  # The test is what tree_state_id measures (git status would follow status.showUntrackedFiles), and the
  # backup goes into the repository's git folder, which cleaning build/ (or git clean -x) does not delete.
  if { [ ! -f "$stamp" ] || [ "$(sed -n 2p "$stamp")" != "$state" ]; } &&
     { ! git -C "$dir" diff HEAD --quiet --no-ext-diff --ignore-submodules ||
       [ -n "$(git -C "$dir" ls-files --others --exclude-standard)" ]; }; then
    backup="$(git rev-parse --git-common-dir 2>/dev/null)" && backup="$(cd "$backup" && pwd)/switch-patch-backups" ||
      backup="$root_dir/build/patch-stamps/backup"
    backup="$backup/$stamp_name-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$backup"
    # A plain diff whatever the diff/color settings, plus a copy of every changed or new file as it is.
    git -C "$dir" diff HEAD --ignore-submodules --binary --no-ext-diff --no-textconv --no-color \
      --src-prefix=a/ --dst-prefix=b/ > "$backup/changes.diff"
    ( cd "$dir" && {
        git diff HEAD -z --name-only --diff-filter=d --no-ext-diff --ignore-submodules
        git ls-files -z --others --exclude-standard
      } | xargs -0 -r cp -r --parents -t "$backup" -- )
    echo "  $dir: its previous changes were saved to $backup (SWITCH_SKIP_PATCHES=1 keeps a hand-edited tree)"
  fi

  # Not recursive whatever submodule.recurse says: nested submodules are reset by their own apply_patches call,
  # after their own backup, or not at all.
  git -C "$dir" -c submodule.recurse=false reset -q --hard HEAD
  git -C "$dir" clean -fdq
  # Nested submodules are separate trees (patched on their own): hunks for their commit ids are skipped.
  local exclude=()
  while IFS= read -r gitlink; do
    exclude+=("--exclude=$gitlink")
  done < <(git -C "$dir" ls-files -s | awk '$1 == "160000" { print $4 }')
  for spec in "$@"; do
    name="${spec#\?}"
    if [ ! -f "patches/$name" ]; then
      [ "$spec" != "$name" ] && continue
      die "  patches/$name is missing."
    fi
    if ! git -C "$dir" apply --check "${apply_flags[@]}" ${exclude[@]+"${exclude[@]}"} "$root_dir/patches/$name" 2>/dev/null; then
      echo "  ERROR: patches/$name does not apply to $dir (after the patches listed before it):" >&2
      git -C "$dir" apply --check -v "${apply_flags[@]}" ${exclude[@]+"${exclude[@]}"} "$root_dir/patches/$name" >&2 || true
      # The half-patched tree is this script's doing, not a hand edit: the next run resets it without a backup.
      mkdir -p build/patch-stamps
      { echo "failed"; tree_state_id "$dir"; } > "$stamp"
      exit 2
    fi
    git -C "$dir" apply "${apply_flags[@]}" ${exclude[@]+"${exclude[@]}"} "$root_dir/patches/$name"
    echo "  $dir: applied $name"
  done
  mkdir -p build/patch-stamps
  { echo "$patches_id"; tree_state_id "$dir"; } > "$stamp"
}
if [ "$SWITCH_SKIP_PATCHES" = "1" ]; then
  echo "  skipped (SWITCH_SKIP_PATCHES=1): the submodule trees are built as they are"
else
  apply_patches thirdparty/plume                         plume.patch plume-switch-perf.patch
  apply_patches thirdparty/plume/contrib/volk            volk.patch
  apply_patches thirdparty/imgui                         imgui.patch
  apply_patches thirdparty/implot                        implot.patch
  apply_patches thirdparty/concurrentqueue               concurrentqueue.patch
  apply_patches tools/XenonRecomp                        XenonRecomp.patch XenonRecomp-switch-perf.patch
  apply_patches tools/XenonRecomp/thirdparty/tomlplusplus tomlplusplus-msys-host.patch
  apply_patches tools/XenosRecomp                        XenosRecomp.patch XenosRecomp-mingw-dxc.patch XenosRecomp-switch-perf.patch
fi

# --------------------------------------------------- 2. host tools (native)
log "2/8 build host tools (native)"
CC="$CLANGARM64/clang.exe" CXX="$CLANGARM64/clang++.exe" \
"$CMAKE" -S . -B build/host-tools -G Ninja -DCMAKE_BUILD_TYPE=Release \
  -DMARATHON_RECOMP_HOST_TOOLS_ONLY=ON -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
  -DCMAKE_CXX_FLAGS="-include cstdlib -include cstdio" -DCMAKE_MAKE_PROGRAM="$NINJA_NATIVE"
"$CMAKE" --build build/host-tools -j"$JOBS" --target XenonRecomp file_to_c u8extract

# ---------------------------- 3. host tool XenosRecomp (x86_64 cross, for x64 DXC)
log "3/8 build XenosRecomp (x64, for x64 DXC)"
PATH="$CLANG64:$DXC_X64:$PATH" CC="$CLANG64/clang.exe" CXX="$CLANG64/clang++.exe" \
"$CMAKE" -S . -B build/host-tools-x64 -G Ninja \
  -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=AMD64 \
  -DCMAKE_BUILD_TYPE=Release -DMARATHON_RECOMP_HOST_TOOLS_ONLY=ON \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
  -DCMAKE_CXX_FLAGS="-include cstdlib -include cstdio" -DCMAKE_MAKE_PROGRAM="$NINJA_NATIVE"
"$CMAKE" --build build/host-tools-x64 -j"$JOBS" --target XenosRecomp

# ------------------------------------------------------- 4. recompile PPC from XEX
log "4/8 recompile PPC from default.xex"
# ppc/ belongs to the recompiler that wrote it (its tree and patches), its inputs and its mode: it is
# generated again only when one of them changes (XenonRecomp itself rewrites only files whose text changes).
codegen_id="$(
  echo "xenonrecomp=$(tree_state_id tools/XenonRecomp)"
  echo "patches=$(patch_list_id XenonRecomp.patch XenonRecomp-switch-perf.patch)"
  echo "marathon_toml=$(file_id MarathonRecompLib/config/Marathon.toml)"
  echo "switch_table_toml=$(file_id MarathonRecompLib/config/switch_table.toml)"
  echo "default_xex=$(file_id MarathonRecompLib/private/default.xex)"
  echo "classic=$SWITCH_CLASSIC_CODEGEN"
  echo "register_locals=$SWITCH_REGISTER_LOCALS"
  echo "fewer_mode_switches=$SWITCH_FEWER_MODE_SWITCHES"
  echo "codegen_pass=$(file_id "$codegen_pass_tool") $codegen_pass_options"
  echo "call_locals_list=$(file_id MarathonRecompLib/config/call_locals.txt)"
  echo "fp_no_contract_list=$(file_id MarathonRecompLib/config/fp_no_contract.txt)"
  # Any other XenonRecomp switch read from the environment.
  env | grep '^XENON_RECOMP_' | grep -v '^XENON_RECOMP_CLASSIC=' | grep -v '^XENON_RECOMP_REGISTER_LOCALS=' |
    grep -v '^XENON_RECOMP_FEWER_MODE_SWITCHES=' | sort || true
)"
if [ -f "$ppc_dir/ppc_recomp.0.cpp" ] && [ -f "$ppc_dir/ppc_func_mapping.cpp" ] &&
   [ "$(cat "$codegen_stamp" 2>/dev/null)" = "$codegen_id" ]; then
  echo "  ppc/ is up to date"
else
  echo "  generating ppc/"
  print_changed_keys "$codegen_stamp" "$codegen_id"
  # Only the generated files: the folder keeps its tracked .gitignore. Stale files of a longer run go too.
  mkdir -p "$ppc_dir" # XenonRecomp does not create it
  find "$ppc_dir" -maxdepth 1 -type f ! -name .gitignore -delete
  codegen_env=(env -u XENON_RECOMP_CLASSIC -u XENON_RECOMP_REGISTER_LOCALS -u XENON_RECOMP_FEWER_MODE_SWITCHES)
  if [ "$SWITCH_CLASSIC_CODEGEN" = "1" ]; then codegen_env=(env XENON_RECOMP_CLASSIC=1); fi
  if [ "$SWITCH_REGISTER_LOCALS" = "1" ]; then codegen_env+=(XENON_RECOMP_REGISTER_LOCALS=1); fi
  if [ "$SWITCH_FEWER_MODE_SWITCHES" = "1" ]; then codegen_env+=(XENON_RECOMP_FEWER_MODE_SWITCHES=1); fi
  "${codegen_env[@]}" build/host-tools/tools/XenonRecomp/XenonRecomp/XenonRecomp.exe \
    MarathonRecompLib/config/Marathon.toml tools/XenonRecomp/XenonUtils/ppc_context.h
  [ -f "$ppc_dir/ppc_recomp.0.cpp" ] || die "XenonRecomp wrote no code to $ppc_dir."
  # The code generation pass (leaf locals, NEON table shuffles, inline FP compare and fixed-size copies, narrow
  # loop barriers) on XenonRecomp's own output, before the direct calls.
  if [ -f "$codegen_pass_tool" ]; then
    require_python
    env $codegen_pass_options "$PYTHON" "$codegen_pass_tool"
  fi
  printf '%s\n' "$codegen_id" > "$codegen_stamp"
fi

fi # SWITCH_APP_ONLY

# Every build, also with SWITCH_APP_ONLY: a hook added to MarathonRecomp/ since the last run must stop the
# direct calls to its function. Idempotent (it undoes its previous run first) and it writes only the files
# whose calls change. The classic A/B build keeps every definition a plain one (no .text.hot section).
if [ "$SWITCH_DIRECT_CALLS" = "1" ]; then
  if $direct_calls_run; then
    echo "  direct calls: $direct_calls_tool apply"
    hot_functions="$SWITCH_HOT_FUNCTIONS"
    if [ "$SWITCH_CLASSIC_CODEGEN" = "1" ]; then hot_functions=0; fi
    SWITCH_HOT_FUNCTIONS="$hot_functions" \
    "$PYTHON" "$direct_calls_tool" apply --ppc "$ppc_dir" --hook-sources MarathonRecomp MarathonRecompLib/config
  else
    echo "  $direct_calls_tool not found: calls between recompiled functions stay through their weak aliases"
  fi
elif [ -f "$direct_calls_manifest" ]; then
  $direct_calls_run || die "$ppc_dir holds direct calls but $direct_calls_tool is missing; delete $codegen_stamp to regenerate ppc/."
  echo "  direct calls: $direct_calls_tool undo (SWITCH_DIRECT_CALLS=0)"
  "$PYTHON" "$direct_calls_tool" undo --ppc "$ppc_dir"
fi

if [ "$SWITCH_APP_ONLY" != "1" ]; then

# --------------------------------------------------------- 5. generate shaders
log "5/8 generate shader cache + app shaders"
U8="build/host-tools/tools/u8extract/u8extract.exe"
XS="build/host-tools-x64/tools/XenosRecomp/XenosRecomp/XenosRecomp.exe"
# The cache holds compiled blobs, so one made by another translator still looks valid: it is made again
# whenever the translator (its tree, patches and submodules), shader_common.h or the game's shaders change.
translator_id="$(
  echo "xenosrecomp=$(tree_state_id tools/XenosRecomp)"
  echo "xenosrecomp_submodules=$(git -C tools/XenosRecomp submodule status | awk '{ print $1, $2 }' | sha256sum | cut -c1-64)"
  echo "patches=$(patch_list_id XenosRecomp.patch XenosRecomp-mingw-dxc.patch XenosRecomp-switch-perf.patch)"
  echo "shader_common_h=$(file_id tools/XenosRecomp/XenosRecomp/shader_common.h)"
  echo "shader_arc=$(file_id MarathonRecompLib/private/shader.arc)"
  echo "shader_lt_arc=$(file_id MarathonRecompLib/private/shader_lt.arc)"
  env | grep '^XENOS_RECOMP_' | sort || true
)"
if [ -f "$shader_cache" ] && [ "$(cat "$shader_stamp" 2>/dev/null)" = "$translator_id" ]; then
  echo "  shader cache is up to date"
else
  echo "  generating the shader cache"
  print_changed_keys "$shader_stamp" "$translator_id"
  rm -rf MarathonRecompLib/private/shader; mkdir -p MarathonRecompLib/private/shader
  "$U8" MarathonRecompLib/private/shader.arc    MarathonRecompLib/private/shader
  "$U8" MarathonRecompLib/private/shader_lt.arc MarathonRecompLib/private/shader
  shader_candidate="$shader_cache.candidate"
  rm -f "$shader_candidate"
  PATH="$CLANG64:$DXC_X64:$PATH" "$XS" MarathonRecompLib/private/shader \
    "$shader_candidate" tools/XenosRecomp/XenosRecomp/shader_common.h
  [ -s "$shader_candidate" ] || die "XenosRecomp wrote no shader cache."
  # An identical cache keeps its timestamp, so the 7.5 MB file is not compiled again.
  if cmp -s "$shader_candidate" "$shader_cache"; then
    rm -f "$shader_candidate"
    echo "  shader cache unchanged"
  else
    mv -f "$shader_candidate" "$shader_cache"
  fi
  printf '%s\n' "$translator_id" > "$shader_stamp"
fi

# App shaders: their sources, what they include (shader_common.h among others), the script and DXC.
app_shader_dir="MarathonRecomp/gpu/shader/hlsl"
app_shader_stamp="build/switch-stamps/app-shaders.stamp"
app_shader_inputs() { # every app shader source and, transitively, the files it includes (sorted)
  local -A seen=()
  local queue=("$app_shader_dir"/*.hlsl "$app_shader_dir"/*.hlsli)
  local file include
  while [ "${#queue[@]}" -gt 0 ]; do
    file="$(realpath -m "${queue[0]}")"
    queue=("${queue[@]:1}")
    if [ -n "${seen[$file]:-}" ] || [ ! -f "$file" ]; then continue; fi
    seen[$file]=1
    while IFS= read -r include; do
      queue+=("$(dirname "$file")/$include")
    done < <(sed -n 's/^[[:space:]]*#[[:space:]]*include[[:space:]]*"\([^"]*\)".*/\1/p' "$file")
  done
  printf '%s\n' "${!seen[@]}" | sort
}
app_shader_id="$(
  echo "script=$(file_id tools/generate-switch-app-shaders.sh)"
  echo "dxc=$(find "$DXC_X64" -maxdepth 1 -type f -print0 | sort -z | xargs -0 sha256sum | cut -c1-64 | sha256sum | cut -c1-64)"
  while IFS= read -r input; do
    echo "${input#"$root_dir/"}=$(file_id "$input")"
  done < <(app_shader_inputs)
)"
app_shaders_present=true
while IFS= read -r app_shader; do
  [ -f "$app_shader_dir/$app_shader.hlsl.spirv.h" ] || app_shaders_present=false
done < <(sed -n 's/^compile_\(pixel\|vertex\)_shader[[:space:]]\+\([A-Za-z0-9_]\+\).*/\2/p' tools/generate-switch-app-shaders.sh)
if $app_shaders_present && [ "$(cat "$app_shader_stamp" 2>/dev/null)" = "$app_shader_id" ]; then
  echo "  app shaders are up to date"
else
  # The script rewrites every header; one whose content did not change keeps its timestamp, so the sources
  # including it are not compiled again.
  app_shader_previous="build/switch-stamps/app-shaders.previous"
  rm -rf "$app_shader_previous"; mkdir -p "$app_shader_previous"
  for header in "$app_shader_dir"/*.hlsl.spirv.h; do
    if [ -f "$header" ]; then cp -p "$header" "$app_shader_previous/"; fi
  done
  bash tools/generate-switch-app-shaders.sh
  for header in "$app_shader_previous"/*.hlsl.spirv.h; do
    if [ -f "$header" ] && cmp -s "$header" "$app_shader_dir/${header##*/}"; then
      touch -r "$header" "$app_shader_dir/${header##*/}"
    fi
  done
  rm -rf "$app_shader_previous"
  printf '%s\n' "$app_shader_id" > "$app_shader_stamp"
fi

# ------------------------------------------------------------------ 6. ffmpeg
log "6/8 cross-build FFmpeg (avcodec+avutil, XMAFRAMES)"
DEVKITPRO="$DEVKITPRO_SHELL" CLANGARM64="$CLANGARM64" JOBS="$JOBS" bash tools/build-switch-ffmpeg.sh

fi # SWITCH_APP_ONLY

# ------------------------------------------------- 7. configure + build the app
# Exact FMA only works with ppc/ text that has the guest's fused operations as explicit fma (written by a
# XenonRecomp with XenonRecomp-switch-perf.patch, not in classic mode): with plain a*b+c text, -ffp-contract=off
# would round every one of them twice. The configure step checks the same.
if [ "$SWITCH_EXACT_FMA" = "1" ] &&
   ! grep -qE 'PPC_FM[AS]\(|simde_mm_v(madd|nmsub)fp\(' "$ppc_dir"/ppc_recomp.*.cpp; then
  echo "  SWITCH_EXACT_FMA=1 is ignored: $ppc_dir has no explicit fma (XenonRecomp-switch-perf.patch not applied?);"
  echo "  GCC's default contraction is used."
  SWITCH_EXACT_FMA=0
fi
if $build_id_default; then
  SWITCH_BUILD_ID="$(date +%Y%m%d-%H%M)"
  if [ "$SWITCH_LTO" = "1" ]; then SWITCH_BUILD_ID+="-lto"; fi
  if [ -n "$SWITCH_PGO" ]; then SWITCH_BUILD_ID+="-pgo-$SWITCH_PGO"; fi
  if [ "$SWITCH_O2" = "1" ]; then SWITCH_BUILD_ID+="-o2"; fi
  if [ "$SWITCH_RECOMP_O2" = "1" ]; then SWITCH_BUILD_ID+="-recomp-o2"; fi
  if [ "$SWITCH_IPA_PTA" = "1" ]; then SWITCH_BUILD_ID+="-ipa-pta"; fi
  if [ "$SWITCH_CLASSIC_CODEGEN" = "1" ]; then SWITCH_BUILD_ID+="-classic"; fi
  if [ "$SWITCH_DIRECT_CALLS" = "0" ]; then SWITCH_BUILD_ID+="-no-direct-calls"; fi
  if [ "$SWITCH_FIXED_X16" = "0" ]; then SWITCH_BUILD_ID+="-no-fixed-x16"; fi
  if [ "$SWITCH_EXACT_FMA" = "1" ]; then SWITCH_BUILD_ID+="-exact-fma"; fi
  if [ "$SWITCH_REGISTER_LOCALS" = "1" ]; then SWITCH_BUILD_ID+="-reglocals"; fi
  if [ "$SWITCH_PLAIN_GUEST_MEMORY" = "1" ]; then SWITCH_BUILD_ID+="-plainmem"; fi
  if [ "$SWITCH_NARROW_BARRIER" = "1" ]; then SWITCH_BUILD_ID+="-narrow"; fi
  if [ "$SWITCH_WIDE_DFORM" = "1" ]; then SWITCH_BUILD_ID+="-wide"; fi
  echo "Build ID: $SWITCH_BUILD_ID"
fi
log "7/8 configure + cross-compile the Switch app ($SWITCH_BUILD_ID)"
cmake_bool() { if [ "$1" = "1" ]; then echo ON; else echo OFF; fi; }
# The code generation ppc/ was written with, from its stamp (the build options line of stderr.log names it): short
# names of the options that are on.
codegen_options_summary() {
  local stamp_text names=""
  stamp_text="$(cat "$codegen_stamp" 2>/dev/null || true)"
  case "$stamp_text" in *"register_locals=1"*) names+=" reglocals" ;; esac
  case "$stamp_text" in *"fewer_mode_switches=1"*) names+=" fewer_modes" ;; esac
  case "$stamp_text" in *"SWITCH_LEAF_LOCALS=1"*) names+=" leaf_locals" ;; esac
  case "$stamp_text" in *"SWITCH_CONST_VMX_TABLES=1"*) names+=" vmx_tables" ;; esac
  case "$stamp_text" in *"SWITCH_INLINE_FP_COMPARE=1"*) names+=" fp_compare" ;; esac
  case "$stamp_text" in *"SWITCH_INLINE_MEMCPY=1"*) names+=" inline_memcpy" ;; esac
  case "$stamp_text" in *"SWITCH_NARROW_BARRIER=1"*) names+=" narrow_barrier" ;; esac
  case "$stamp_text" in *"SWITCH_WIDE_DFORM=1"*) names+=" wide_dform" ;; esac
  case "$stamp_text" in *"SWITCH_CALL_LOCALS=1"*) names+=" call_locals" ;; esac
  case "$stamp_text" in *"SWITCH_FPSCR_LOCALS=1"*) names+=" fpscr_locals" ;; esac
  case "$stamp_text" in *"SWITCH_PREFETCH_HINTS=1"*) names+=" prefetch_hints" ;; esac
  case "$stamp_text" in *"SWITCH_FP_LEAF_LOCALS=1"*) names+=" fp_leaf_locals" ;; esac
  case "$stamp_text" in *"SWITCH_FP_SINGLE_MODE=1"*) names+=" fp_single_mode" ;; esac
  case "$stamp_text" in *"SWITCH_FP_NO_CONTRACT=1"*) names+=" fp_no_contract" ;; esac
  case "$stamp_text" in *"SWITCH_FP_INT_LOCALS=1"*) names+=" fp_int_locals" ;; esac
  if [ "$SWITCH_DIRECT_CALLS" = "1" ] && [ "$SWITCH_HOT_FUNCTIONS" = "1" ] && [ "$SWITCH_CLASSIC_CODEGEN" != "1" ]; then
    names+=" hot_functions"
  fi
  echo "${names# }"
}
# Windows form: libnx's switch.specs reads DEVKITPRO when the app is linked.
export DEVKITPRO
PATH="$DEVKITPRO_SHELL/devkitA64/bin:$PATH" \
"$CMAKE" -S . -B build/switch-app -G Ninja \
  -DCMAKE_TOOLCHAIN_FILE=toolchains/switch-devkitA64.cmake -DCMAKE_BUILD_TYPE=Release \
  -DDEVKITPRO="$DEVKITPRO" \
  -DMARATHON_RECOMP_SWITCH=ON \
  -DMARATHON_RECOMP_SWITCH_USE_PREGENERATED_SHADERS=ON \
  -DMARATHON_RECOMP_SWITCH_USE_PREGENERATED_APP_SHADERS=ON \
  -DMARATHON_RECOMP_SWITCH_USE_PREGENERATED_PPC=ON \
  -DMARATHON_RECOMP_HOST_TOOLS_DIR="$root_native/build/host-tools" \
  -DMARATHON_RECOMP_HOST_FILE_TO_C="$root_native/build/host-tools/tools/file_to_c/file_to_c.exe" \
  -DPLUME_PLATFORM_SWITCH=ON -DPLUME_SWITCH_NVK_ROOT="$NVK_ROOT" -DPLUME_SWITCH_NVK_LIBRARY="$NVK_LIB" \
  -DPLUME_SWITCH_NVK_EXTRA_LIBS="$NVK_EXTRA_LIBS" \
  -DMARATHON_RECOMP_SWITCH_LTO="$(cmake_bool "$SWITCH_LTO")" \
  -DMARATHON_RECOMP_SWITCH_LTO_JOBS="$SWITCH_LTO_JOBS" \
  -DMARATHON_RECOMP_SWITCH_PGO="$SWITCH_PGO" \
  -DMARATHON_RECOMP_SWITCH_PGO_DIR="$SWITCH_PGO_DIR" \
  -DMARATHON_RECOMP_SWITCH_O2="$(cmake_bool "$SWITCH_O2")" \
  -DMARATHON_RECOMP_SWITCH_RECOMP_O2="$(cmake_bool "$SWITCH_RECOMP_O2")" \
  -DMARATHON_RECOMP_SWITCH_IPA_PTA="$(cmake_bool "$SWITCH_IPA_PTA")" \
  -DMARATHON_RECOMP_SWITCH_CLASSIC_CODEGEN="$(cmake_bool "$SWITCH_CLASSIC_CODEGEN")" \
  -DMARATHON_RECOMP_SWITCH_FIXED_X16="$(cmake_bool "$SWITCH_FIXED_X16")" \
  -DMARATHON_RECOMP_SWITCH_EXACT_FMA="$(cmake_bool "$SWITCH_EXACT_FMA")" \
  -DMARATHON_RECOMP_SWITCH_PLAIN_GUEST_MEMORY="$(cmake_bool "$SWITCH_PLAIN_GUEST_MEMORY")" \
  -DMARATHON_RECOMP_SWITCH_CODEGEN_OPTIONS="$(codegen_options_summary)" \
  -DMARATHON_RECOMP_SWITCH_BUILD_ID="$SWITCH_BUILD_ID" \
  -DCMAKE_MAKE_PROGRAM="$NINJA_NATIVE"
PATH="$DEVKITPRO_SHELL/devkitA64/bin:$PATH" "$CMAKE" --build build/switch-app -j"$JOBS" --target MarathonRecomp

if [ "$SWITCH_DIRECT_CALLS" = "1" ] && $direct_calls_run; then
  # Every sub_X in the ELF that is not an alias of its __imp__sub_X body is a hook; none of them may have been
  # bypassed by a direct call. A failure here means ppc/ holds direct calls to a hooked function.
  switch_nm="$DEVKITPRO/devkitA64/bin/aarch64-none-elf-nm"
  if [ -f "$DEVKITPRO_SHELL/devkitA64/bin/aarch64-none-elf-nm.exe" ]; then switch_nm="$switch_nm.exe"; fi
  "$PYTHON" "$direct_calls_tool" verify-elf --elf build/switch-app/MarathonRecomp/MarathonRecomp --nm "$switch_nm"
fi

# ------------------------------------------------------------------ 8. package
log "8/8 package NRO"
DEVKITPRO="$DEVKITPRO_SHELL" bash tools/package-switch-nro.sh

echo; echo "==== Switch build complete: dist/switch/MarathonRecomp.nro (build $SWITCH_BUILD_ID) ===="
