#!/usr/bin/env python3
"""Generates placeholder MarathonRecompLib/ppc sources for compile validation.

XenonRecomp needs the game binary (MarathonRecompLib/private/default.xex) to
produce the real recompiled sources. This script creates stand-in files with
the same layout so the Switch (or any) build can be compiled end-to-end
without game files. The resulting binary is NOT runnable: every guest
function body is missing and the image constants are guesses.

Run tools/build-switch-nro.sh with real game files to replace these stubs
with the actual XenonRecomp output.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PPC_DIR = ROOT / "MarathonRecompLib" / "ppc"
APP_DIR = ROOT / "MarathonRecomp"
CONTEXT_HEADER = ROOT / "tools" / "XenonRecomp" / "XenonUtils" / "ppc_context.h"
NUM_RECOMP_FILES = 146

BANNER = "// STUB generated by tools/generate-switch-ppc-stubs.py - replace with real XenonRecomp output.\n"

def collect_symbols():
    pattern = re.compile(r"\bsub_[0-9A-Fa-f]{8}\b")
    symbols = set()
    for path in APP_DIR.rglob("*"):
        if path.suffix not in (".cpp", ".h", ".inl"):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        symbols.update(pattern.findall(text))
    return sorted(symbols)

def main():
    if not CONTEXT_HEADER.exists():
        sys.exit(f"missing {CONTEXT_HEADER}")

    PPC_DIR.mkdir(parents=True, exist_ok=True)

    symbols = collect_symbols()
    print(f"found {len(symbols)} referenced guest symbols")

    config = BANNER + """#pragma once
#ifndef PPC_CONFIG_H_INCLUDED
#define PPC_CONFIG_H_INCLUDED

#define PPC_IMAGE_BASE 0x82000000ull
#define PPC_IMAGE_SIZE 0x4000000ull

#define PPC_CODE_BASE 0x82010000ull
#define PPC_CODE_SIZE 0x1000000ull

#ifdef PPC_INCLUDE_DETAIL
#include "ppc_detail.h"
#endif

#endif
"""
    (PPC_DIR / "ppc_config.h").write_text(config, encoding="utf-8")

    context = BANNER + "#pragma once\n#include \"ppc_config.h\"\n\n"
    context += CONTEXT_HEADER.read_text(encoding="utf-8")
    (PPC_DIR / "ppc_context.h").write_text(context, encoding="utf-8")

    shared = BANNER + "#pragma once\n\n#include \"ppc_config.h\"\n#include \"ppc_context.h\"\n\n"
    shared += "".join(f"PPC_EXTERN_FUNC({name});\n" for name in symbols)
    (PPC_DIR / "ppc_recomp_shared.h").write_text(shared, encoding="utf-8")

    mapping = BANNER + "#include \"ppc_recomp_shared.h\"\n\n"
    mapping += "PPCFuncMapping PPCFuncMappings[] = {\n\t{ 0, nullptr }\n};\n"
    (PPC_DIR / "ppc_func_mapping.cpp").write_text(mapping, encoding="utf-8")

    for i in range(NUM_RECOMP_FILES):
        (PPC_DIR / f"ppc_recomp.{i}.cpp").write_text(
            BANNER + "#include \"ppc_recomp_shared.h\"\n", encoding="utf-8")

    print(f"wrote stub sources to {PPC_DIR}")

if __name__ == "__main__":
    main()
